name: erudio.sklearn
channels:
  - intel
  - conda-forge
dependencies:
  - python=3.12
  - scikit-learn
  - hdbscan
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - seaborn
  - pillow
  - graphviz
  - pygraphviz
  - pyamg
  - jupyterlab
  - scikit-learn-intelex
