name: erudio.sklearn.nographviz
channels:
  - conda-forge
  - intel
dependencies:
  - python=3.11 # for pyarrow
  - scikit-learn
  - hdbscan
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - seaborn
  - pillow
  - pyamg
  - jupyterlab
  - jupyterlab-myst
  - pyarrow
