name: erudio.sklearn
channels:
  - conda-forge
  - intel
dependencies:
  - python=3.11 # for pyarrow
  - scikit-learn
  - hdbscan
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - seaborn
  - pillow
  - graphviz
  - pygraphviz
  - pyamg
  - jupyterlab
  - scikit-learn-intelex
  - jupyterlab-myst
  - pyarrow
